# Generated by Django 5.2 on 2025-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
